services:
  mysql:
    image: mysql:9.4
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: student_db
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cc-network

  campuscore:
    build: .
    image: campuscore:1.0
    container_name: campus-core
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_db
    networks:
      - cc-network
volumes:
  mysql-data:
networks:
  cc-network:
    driver: bridge






